#source(paste(ScriptPath,"EvaluationStats.r",sep="\\"))
source(paste(ScriptPath,"TestTrainRocPlot.r",sep="\\"))
source(paste(ScriptPath,"read.ma.r",sep="\\"))
source(paste(ScriptPath,"proc.tiff.r",sep="\\"))
source(paste(ScriptPath,"check.libs.r",sep="\\"))
source(paste(ScriptPath,"modalDialog.r",sep="\\"))
#replace EvaluationStats with
source(paste(ScriptPath,"make.auc.r",sep="\\"))
#source(paste(ScriptPath,"make.poisson.plot.r",sep="\\"))
#source(paste(ScriptPath,"make.auc.plot.r",sep="\\"))
source(paste(ScriptPath,"EvalStats.r",sep="\\"))
source(paste(ScriptPath,"EvalStatsHelperFcts.r",sep="\\"))
source(paste(ScriptPath,"AppendOut.r",sep="\\"))
source(paste(ScriptPath,"ResidualImage.r",sep="\\"))
source(paste(ScriptPath,"Pred.Surface.r",sep="\\"))
#Fit.Mars
