import core.modules.module_registry
from core.modules.vistrails_module import Module, ModuleError
from obvious.viz import Visualization
from obvious.view import JView, JViewFactory
from javax.swing import JFrame
from java.lang import System

version = "0.0.1"
name = "ObviousView"
identifier = "com.googlecode.obvious.view.JView"
class ObviousView(Module):
    
    def compute(self):
        vis = self.getInputConnector("visualization")
        viewFactoryName = self.getInputConnector("viewFactoryName")
        System.setProperty("obvious.JViewFactory", viewFactoryName)
        factory = JViewFactory.getInstance()
        jview = factory.createJView(vis)
        jcomp = jview.getViewJComponent()
        frame = JFrame("Frame generated by vistrails-obvious")
        frame.add(jcomp)
        frame.setVisible(True)
        frame.pack()
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE)
        self.setResult("jframe", frame)
        

def initialize(*args, **keywords):
    reg = core.modules.module_registry.registry
    reg.addModule(ObviousView)
    reg.add_input_port(ObviousView, "visualization",
                       (Visualization, "obvious visualization"))
    reg.add_input_port(ObviousView, "viewFactoryName"
                       (core.modules.basic_modules.String, "name of the viewfactory"))
    reg.add_output_port(ObviousView, "jframe",
                        (JFrame, "Resulting JFrame"))