from core.modules.vistrails_module import Module
# from obvious.view import JView, JViewFactory
# from javax.swing import JFrame
# from java.lang import System

class ObviousView(Module):
    def compute(self):
        # vis = self.getInputConnector('visualization')
        # viewFactoryName = self.getInputConnector('viewFactoryName')
        # System.setProperty('obvious.JViewFactory', viewFactoryName)
        # factory = JViewFactory.getInstance()
        # jview = factory.createJView(vis)
        # jcomp = jview.getViewJComponent()
        # frame = JFrame("Frame generated by vistrails-obvious")
        # frame.add(jcomp)
        # frame.setVisible(True)
        # frame.pack()
        # frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE)
        # self.setResult('jframe', frame)
        self.setResult('jframe', '!!jframe!!')
